site_name: My Docs
theme:
  #name: 'readthedocs'
  name: 'material'
  #feature:
  #  tabs: true
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

plugins:
  - search

extra_javascript:
    - https://unpkg.com/mermaid@8.4.5/dist/mermaid.min.js
    - https://unpkg.com/jquery@3.4.1/dist/jquery.min.js

